apiVersion: v1
kind: Pod
metadata:
  name: gpu-test
spec:
  containers:
    - name: gpu-test
      image: tanvir/nlp-starter
      imagePullPolicy: Never
      resources:
        limits:
          nvidia.com/gpu: 1 # requesting 1 GPUs
      command:
        - ./.env/bin/python3
        - cuda.py